### ISSUE TITLE
Add CI workflows to enhance the dev experience

### ISSUE THREAD

**Issue by umbynos** [arduino/imgtool-packing#17]
Add some checks workflows to this repo to enhance the developer experience and to catch common problems:
 - https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-markdown-task.md
 - https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-taskfiles.md
 - https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-workflows-task.md
 - https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-shell-task.md
 - https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/check-license.md

**Comment by MatteoPologruto** [comment]
Checks added in the following PRs:
- check markdown: #18 
- check license: #19 
- check taskfiles: #20 
- check workflows: #21 
- check shell: #22
